namespace Extractor;

[SeanItem(101)]
public struct PetLevelup {
    [SeanField(0)] public int Id { get; set; }

    [SeanField(1)] public int Unknown1 { get; set; }
    [SeanField(2)] public int Unknown2 { get; set; }
    [SeanField(3)] public int Unknown3 { get; set; }
    [SeanField(4)] public int Unknown4 { get; set; }
    [SeanField(5)] public int Unknown5 { get; set; }
    [SeanField(6)] public int Unknown6 { get; set; }
    [SeanField(7)] public int Unknown7 { get; set; }
    [SeanField(8)] public int Unknown8 { get; set; }
    [SeanField(9)] public int Unknown9 { get; set; }
    [SeanField(10)] public int Unknown10 { get; set; }
    [SeanField(11)] public int Unknown11 { get; set; }
    [SeanField(12)] public int Unknown12 { get; set; }
    [SeanField(13)] public int Unknown13 { get; set; }
    [SeanField(14)] public int Unknown14 { get; set; }
    [SeanField(15)] public int Unknown15 { get; set; }
    [SeanField(16)] public int Unknown16 { get; set; }
    [SeanField(17)] public int Unknown17 { get; set; }
    [SeanField(18)] public int Unknown18 { get; set; }
    [SeanField(19)] public int Unknown19 { get; set; }
    [SeanField(20)] public int Unknown20 { get; set; }
    [SeanField(21)] public int Unknown21 { get; set; }
    [SeanField(22)] public int Unknown22 { get; set; }
    [SeanField(23)] public int Unknown23 { get; set; }
    [SeanField(24)] public int Unknown24 { get; set; }
    [SeanField(25)] public int Unknown25 { get; set; }
    [SeanField(26)] public int Unknown26 { get; set; }
    [SeanField(27)] public int Unknown27 { get; set; }
    [SeanField(28)] public int Unknown28 { get; set; }
    [SeanField(29)] public int Unknown29 { get; set; }
    [SeanField(30)] public int Unknown30 { get; set; }
    [SeanField(31)] public int Unknown31 { get; set; }
    [SeanField(32)] public int Unknown32 { get; set; }
    [SeanField(33)] public int Unknown33 { get; set; }
    [SeanField(34)] public int Unknown34 { get; set; }
    [SeanField(35)] public int Unknown35 { get; set; }
    [SeanField(36)] public int Unknown36 { get; set; }
    [SeanField(37)] public int Unknown37 { get; set; }
    [SeanField(38)] public int Unknown38 { get; set; }
    [SeanField(39)] public int Unknown39 { get; set; }
    [SeanField(40)] public int Unknown40 { get; set; }
    [SeanField(41)] public int Unknown41 { get; set; }
    [SeanField(42)] public int Unknown42 { get; set; }
    [SeanField(43)] public int Unknown43 { get; set; }
    [SeanField(44)] public int Unknown44 { get; set; }
    [SeanField(45)] public int Unknown45 { get; set; }
    [SeanField(46)] public int Unknown46 { get; set; }
    [SeanField(47)] public int Unknown47 { get; set; }
    [SeanField(48)] public int Unknown48 { get; set; }
    [SeanField(49)] public int Unknown49 { get; set; }
    [SeanField(50)] public int Unknown50 { get; set; }
    [SeanField(51)] public int Unknown51 { get; set; }
    [SeanField(52)] public int Unknown52 { get; set; }
    [SeanField(53)] public int Unknown53 { get; set; }
    [SeanField(54)] public int Unknown54 { get; set; }
    [SeanField(55)] public int Unknown55 { get; set; }
    [SeanField(56)] public int Unknown56 { get; set; }
    [SeanField(57)] public int Unknown57 { get; set; }
    [SeanField(58)] public int Unknown58 { get; set; }
    [SeanField(59)] public int Unknown59 { get; set; }
    [SeanField(60)] public int Unknown60 { get; set; }
    [SeanField(61)] public int Unknown61 { get; set; }
    [SeanField(62)] public int Unknown62 { get; set; }
    [SeanField(63)] public int Unknown63 { get; set; }
    [SeanField(64)] public int Unknown64 { get; set; }
    [SeanField(65)] public int Unknown65 { get; set; }
    [SeanField(66)] public int Unknown66 { get; set; }
    [SeanField(67)] public int Unknown67 { get; set; }
    [SeanField(68)] public int Unknown68 { get; set; }
    [SeanField(69)] public int Unknown69 { get; set; }
    [SeanField(70)] public int Unknown70 { get; set; }
    [SeanField(71)] public int Unknown71 { get; set; }
    [SeanField(72)] public int Unknown72 { get; set; }
    [SeanField(73)] public int Unknown73 { get; set; }
    [SeanField(74)] public int Unknown74 { get; set; }
    [SeanField(75)] public int Unknown75 { get; set; }
    [SeanField(76)] public int Unknown76 { get; set; }
    [SeanField(77)] public int Unknown77 { get; set; }
    [SeanField(78)] public int Unknown78 { get; set; }
    [SeanField(79)] public int Unknown79 { get; set; }
    [SeanField(80)] public int Unknown80 { get; set; }
    [SeanField(81)] public int Unknown81 { get; set; }
    [SeanField(82)] public int Unknown82 { get; set; }
    [SeanField(83)] public int Unknown83 { get; set; }
    [SeanField(84)] public int Unknown84 { get; set; }
    [SeanField(85)] public int Unknown85 { get; set; }
    [SeanField(86)] public int Unknown86 { get; set; }
    [SeanField(87)] public int Unknown87 { get; set; }
    [SeanField(88)] public int Unknown88 { get; set; }
    [SeanField(89)] public int Unknown89 { get; set; }
    [SeanField(90)] public int Unknown90 { get; set; }
    [SeanField(91)] public int Unknown91 { get; set; }
    [SeanField(92)] public int Unknown92 { get; set; }
    [SeanField(93)] public int Unknown93 { get; set; }
    [SeanField(94)] public int Unknown94 { get; set; }
    [SeanField(95)] public int Unknown95 { get; set; }
    [SeanField(96)] public int Unknown96 { get; set; }
    [SeanField(97)] public int Unknown97 { get; set; }
    [SeanField(98)] public int Unknown98 { get; set; }
    [SeanField(99)] public int Unknown99 { get; set; }
    [SeanField(100)] public int Unknown100 { get; set; }
}
